### PR TITLE
Browserify + Lambda server test POST call

### PR DESCRIPTION
**Pull request by jbax1899**
New node module spotify-web-api-js.
New node module browserify, used to package the Spotify api for browser.
Test ajax POST call to the lambda server.

### CODE REVIEW

**Review by AirmanEpic — CHANGES_REQUESTED** [review]
Please add "package.js" and "package-unrendered.js" to the .eslintignore file. This will make it so whinebot doesn't object. I'd also be happy to work with you to get eslint working on your machine so you can check for objections before they make it to the server.

**Review by Mercerenies — CHANGES_REQUESTED** [review]
`fail:` is not an option to `ajax`. `success:` and `error:` are options. `.fail()` is a method that can be called on an ajax object which behaves somewhat like `error:`. You should only need one of the two.

**Comment by jbax1899** [comment]
> Please add "package.js" and "package-unrendered.js" to the .eslintignore file. This will make it so whinebot doesn't object. I'd also be happy to work with you to get eslint working on your machine so you can check for objections before they make it to the server.

Fixed. Will try to set that up myself, might ask you for help in the future. Thanks!


> `fail:` is not an option to `ajax`. `success:` and `error:` are options. `.fail()` is a method that can be called on an ajax object which behaves somewhat like `error:`. You should only need one of the two.

Fixed.

**Review by AirmanEpic — APPROVED** [review]
LGTM 👍

**Review by Mercerenies — APPROVED** [review]
Looks good!

**Pull request merged**
